services:
  redis:
    image: redis
    container_name: my-redis
    ports:
      - "6379:6379"
  
  pub-sub:
    image: redis
    container_name: pub-sub
    ports:
      - "6380:6379"

  api-engine-pubsub:
    image: redis
    container_name: api-engine-pubsub
    ports:
      - "6381:6379"
  database:
    image: postgres
    container_name: database
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
  api-server:
    image: api-server
    container_name: api-server
    ports:
      - "3000:3000"
    depends_on:
      - redis
  exchange-app:
    image: exchange-app
    container_name: exchange-app
    ports:
      - "5173:5173"
    depends_on:
      - api-server
  engine:
    image: engine
    container_name: engine
    ports:
      - "3001:3001"
    depends_on:
      - redis
      - pub-sub
  
  websocket-server:
    image: websocket-server
    container_name: websocket-server
    ports:
      - "8080:8080"
  